"""V-World 전 레이어를 실제로 조사해 벡터가 나온 것들. 손대지 말 것 —
조사 스크립트가 다시 만든다. 2026-08-06, 132건 전수 조사."""

AUTO = [
    ("t_c_wgispl2con", "(2차) 관리연안해역", "해양 · 수자원", "LT_C_WGISPL2CON", "data"),
    ("t_c_wgispl2spa", "(2차) 특수연안해역", "해양 · 수자원", "LT_C_WGISPL2SPA", "data"),
    ("t_c_landinfobasemap", "LX맵", "산업 · 개발", "LT_C_LANDINFOBASEMAP", "data"),
    ("t_c_dhsch", "고등학교학교군", "교육 · 학군", "LT_C_DHSCH", "data"),
    ("t_p_sgisgolf", "골프장현황도", "생활 · 관광", "LT_P_SGISGOLF", "data"),
    ("t_c_wgisreplan", "공유수면매립기본계획", "해양 · 수자원", "LT_C_WGISREPLAN", "data"),
    ("t_c_wgisrecomp", "공유수면매립준공", "해양 · 수자원", "LT_C_WGISRECOMP", "data"),
    ("t_p_dgtouristinfo", "관광안내소", "생활 · 관광", "LT_P_DGTOURISTINFO", "data"),
    ("t_c_uo601", "관광지", "생활 · 관광", "LT_C_UO601", "data"),
    ("t_c_aisctrc", "관제권", "항공 · 군사", "LT_C_AISCTRC", "data"),
    ("t_c_eadist", "교육행정구역", "교육 · 학군", "LT_C_EADIST", "data"),
    ("t_p_utiscctv", "교통CCTV", "생활 · 관광", "LT_P_UTISCCTV", "data"),
    ("t_p_moctnode", "교통노드", "기타 주제도", "LT_P_MOCTNODE", "data"),
    ("t_p_nsnmssitenm", "국가지명", "생활 · 관광", "LT_P_NSNMSSITENM", "data"),
    ("t_c_wgisnpgug", "국립자연공원", "기타 주제도", "LT_C_WGISNPGUG", "data"),
    ("t_c_ud610", "국민임대주택", "산업 · 개발", "LT_C_UD610", "data"),
    ("t_c_uq141", "국토계획구역", "공공 · 행정", "LT_C_UQ141", "data"),
    ("t_c_aismoac", "군작전구역", "항공 · 군사", "LT_C_AISMOAC", "data"),
    ("t_p_mgprtfd", "기타보호시설", "기타 주제도", "LT_P_MGPRTFD", "data"),
    ("t_p_mgprtfb", "노인복지시설", "생활 · 관광", "LT_P_MGPRTFB", "data"),
    ("t_c_damdan", "단지경계", "산업 · 개발", "LT_C_DAMDAN", "data"),
    ("t_c_damyoj", "단지시설용지", "산업 · 개발", "LT_C_DAMYOJ", "data"),
    ("t_c_damyod", "단지용도지역", "산업 · 개발", "LT_C_DAMYOD", "data"),
    ("t_c_damyuch", "단지유치업종", "산업 · 개발", "LT_C_DAMYUCH", "data"),
    ("t_l_gimsfault", "단층", "환경 · 지질", "LT_L_GIMSFAULT", "data"),
    ("t_c_wkmbbsn", "대권역", "해양 · 수자원", "LT_C_WKMBBSN", "data"),
    ("t_l_n3a0020000", "도로중심선", "기타 주제도", "LT_L_N3A0020000", "data"),
    ("t_l_frstclimb", "등산로", "생활 · 관광", "LT_L_FRSTCLIMB", "data"),
    ("t_p_dgmuseumart", "박물관미술관", "생활 · 관광", "LT_P_DGMUSEUMART", "data"),
    ("t_c_aisadzc", "방공식별구역", "항공 · 군사", "LT_C_AISADZC", "data"),
    ("t_c_asitsoildra", "배수등급", "환경 · 지질", "LT_C_ASITSOILDRA", "data"),
    ("t_c_uh701", "벤처기업육성지역", "산업 · 개발", "LT_C_UH701", "data"),
    ("t_c_ud620", "보금자리주택", "산업 · 개발", "LT_C_UD620", "data"),
    ("t_c_aisprhc", "비행금지구역", "항공 · 군사", "LT_C_AISPRHC", "data"),
    ("t_c_aisfirc", "비행정보구역", "항공 · 군사", "LT_C_AISFIRC", "data"),
    ("t_c_aisresc", "비행제한구역", "항공 · 군사", "LT_C_AISRESC", "data"),
    ("t_c_lhzone", "사업지구경계도", "산업 · 개발", "LT_C_LHZONE", "data"),
    ("t_c_fsdifrsts", "산림입지도", "환경 · 지질", "LT_C_FSDIFRSTS", "data"),
    ("t_c_kfdrssigugrade", "산불위험예측지도", "환경 · 지질", "LT_C_KFDRSSIGUGRADE", "data"),
    ("t_c_usfsffb", "소방서관할구역", "공공 · 행정", "LT_C_USFSFFB", "data"),
    ("t_c_gimshydro", "수문지질단위", "환경 · 지질", "LT_C_GIMSHYDRO", "data"),
    ("t_c_gimsstiff", "수질다이어그램", "환경 · 지질", "LT_C_GIMSSTIFF", "data"),
    ("t_p_weissitemf", "수질측정망도시관류지점", "환경 · 지질", "LT_P_WEISSITEMF", "data"),
    ("t_p_weissitema", "수질측정망하천수지점", "환경 · 지질", "LT_P_WEISSITEMA", "data"),
    ("t_l_aisvfrpath", "시계비행로", "항공 · 군사", "LT_L_AISVFRPATH", "data"),
    ("t_p_aisvfrpath", "시계비행로(점)", "항공 · 군사", "LT_P_AISVFRPATH", "data"),
    ("t_c_ub901", "시장정비구역", "산업 · 개발", "LT_C_UB901", "data"),
    ("t_c_asitdeepsoil", "심토토성", "환경 · 지질", "LT_C_ASITDEEPSOIL", "data"),
    ("t_p_mgprtfc", "아동복지시설", "생활 · 관광", "LT_P_MGPRTFC", "data"),
    ("t_p_mgprtfa", "아동안전지킴이집", "생활 · 관광", "LT_P_MGPRTFA", "data"),
    ("t_c_uj401", "온천지구", "생활 · 관광", "LT_C_UJ401", "data"),
    ("t_c_aisdngc", "위험구역", "항공 · 군사", "LT_C_AISDNGC", "data"),
    ("t_c_asitsoildep", "유효토심", "환경 · 지질", "LT_C_ASITSOILDEP", "data"),
    ("t_c_wgisieilban", "일반산업단지", "산업 · 개발", "LT_C_WGISIEILBAN", "data"),
    ("t_c_asitsurston", "자갈함량", "환경 · 지질", "LT_C_ASITSURSTON", "data"),
    ("t_p_bycracks", "자전거보관소", "생활 · 관광", "LT_P_BYCRACKS", "data"),
    ("t_p_smalllibrary", "작은도서관", "생활 · 관광", "LT_P_SMALLLIBRARY", "data"),
    ("t_l_gimsec", "전기전도도", "환경 · 지질", "LT_L_GIMSEC", "data"),
    ("t_p_tradsijang", "전통시장현황", "생활 · 관광", "LT_P_TRADSIJANG", "data"),
    ("t_c_aistmac", "접근관제구역", "항공 · 군사", "LT_C_AISTMAC", "data"),
    ("t_l_aisrouteu", "제한고도", "항공 · 군사", "LT_L_AISROUTEU", "data"),
    ("t_c_dgmainbiz", "주요상권", "산업 · 개발", "LT_C_DGMAINBIZ", "data"),
    ("t_c_wkmmbsn", "중권역", "해양 · 수자원", "LT_C_WKMMBSN", "data"),
    ("t_c_dmsch", "중학교학교군", "교육 · 학군", "LT_C_DMSCH", "data"),
    ("t_c_gimslinea", "지질구조밀도", "환경 · 지질", "LT_C_GIMSLINEA", "data"),
    ("t_l_gimslinea", "지질구조선", "환경 · 지질", "LT_L_GIMSLINEA", "data"),
    ("t_l_gimsdepth", "지하수등수심선", "환경 · 지질", "LT_L_GIMSDEPTH", "data"),
    ("t_l_gimspoten", "지하수등수위선", "환경 · 지질", "LT_L_GIMSPOTEN", "data"),
    ("t_l_gimsdirec", "지하수유동방향", "환경 · 지질", "LT_L_GIMSDIREC", "data"),
    ("t_p_sgisgwchg", "지하수측정망(오염우려지역)", "환경 · 지질", "LT_P_SGISGWCHG", "data"),
    ("t_p_busiincubator", "창업보육센터", "산업 · 개발", "LT_P_BUSIINCUBATOR", "data"),
    ("t_c_wgisiedosi", "첨단산업단지", "산업 · 개발", "LT_C_WGISIEDOSI", "data"),
    ("t_c_desch", "초등학교통학구역", "교육 · 학군", "LT_C_DESCH", "data"),
    ("t_c_gimsscs", "토양도", "환경 · 지질", "LT_C_GIMSSCS", "data"),
    ("t_c_lhblpn", "토지이용계획도", "산업 · 개발", "LT_C_LHBLPN", "data"),
    ("t_l_aiscorrid_ys", "한강회랑", "항공 · 군사", "LT_L_AISCORRID_YS", "data"),
    ("t_l_aiscorrid_gj", "한강회랑(선)", "항공 · 군사", "LT_L_AISCORRID_GJ", "data"),
    ("t_p_aiscorrid_ys", "한강회랑(점)", "항공 · 군사", "LT_P_AISCORRID_YS", "data"),
    ("t_p_aiscorrid_gj", "한강회랑(gj)", "항공 · 군사", "LT_P_AISCORRID_GJ", "data"),
    ("t_l_aispath", "항공로", "항공 · 군사", "LT_L_AISPATH", "data"),
    ("t_l_toisdepcntah", "해안선", "해양 · 수자원", "LT_L_TOISDEPCNTAH", "data"),
    ("t_p_aishcstrip", "헬기장", "항공 · 군사", "LT_P_AISHCSTRIP", "data"),
    ("t_c_wgispl2abs", "(2차) 보전연안해역", "해양 · 수자원", "LT_C_WGISPL2ABS", "wfs"),
    ("t_c_wgispl2use", "(2차) 이용연안해역", "해양 · 수자원", "LT_C_WGISPL2USE", "wfs"),
    ("t_c_aisuac", "(UA)초경량비행장치공역", "항공 · 군사", "LT_C_AISUAC", "wfs"),
    ("t_c_cademd", "(센서스경계)행정동경계", "공공 · 행정", "LT_C_CADEMD", "wfs"),
    ("t_c_aisaltc", "경계구역", "항공 · 군사", "LT_C_AISALTC", "wfs"),
    ("t_c_aisfldc", "경량항공기이착륙장", "항공 · 군사", "LT_C_AISFLDC", "wfs"),
    ("t_c_aisrflc", "공중급유구역", "항공 · 군사", "LT_C_AISRFLC", "wfs"),
    ("t_c_aisacmc", "공중전투기동훈련장", "항공 · 군사", "LT_C_AISACMC", "wfs"),
    ("t_c_c4speedbump", "과속방지턱", "기타 주제도", "LT_C_C4SPEEDBUMP", "wfs"),
    ("t_c_adsido", "광역시도", "공공 · 행정", "LT_C_ADSIDO", "wfs"),
    ("t_c_wgisiegug", "국가산업단지", "산업 · 개발", "LT_C_WGISIEGUG", "wfs"),
    ("t_c_wgisnpgun", "군립자연공원", "기타 주제도", "LT_C_WGISNPGUN", "wfs"),
    ("t_l_b2surfacelinemark", "노면선표시", "기타 주제도", "LT_L_B2SURFACELINEMARK", "wfs"),
    ("t_c_b3surfacemark", "노면표시", "기타 주제도", "LT_C_B3SURFACEMARK", "wfs"),
    ("t_c_wgisienong", "농공단지", "산업 · 개발", "LT_C_WGISIENONG", "wfs"),
    ("t_l_c5heightbarrier", "높이장애물", "기타 주제도", "LT_L_C5HEIGHTBARRIER", "wfs"),
    ("t_c_spbd", "도로명주소건물", "기타 주제도", "LT_C_SPBD", "wfs"),
    ("t_c_wgisnpdo", "도립자연공원", "기타 주제도", "LT_C_WGISNPDO", "wfs"),
    ("t_c_aisdronezone", "드론시범사업구역", "기타 주제도", "LT_C_AISDRONEZONE", "wfs"),
    ("t_p_climball", "등산로(점)", "생활 · 관광", "LT_P_CLIMBALL", "wfs"),
    ("t_c_adri", "리", "기타 주제도", "LT_C_ADRI", "wfs"),
    ("t_c_a4subsidiarysection", "보도구간", "기타 주제도", "LT_C_A4SUBSIDIARYSECTION", "wfs"),
    ("t_c_aisatzc", "비행장교통구역", "항공 · 군사", "LT_C_AISATZC", "wfs"),
    ("t_l_aissearchl", "수색비행장비행구역", "항공 · 군사", "LT_L_AISSEARCHL", "wfs"),
    ("t_p_aissearchp", "수색비행장비행구역(점)", "항공 · 군사", "LT_P_AISSEARCHP", "wfs"),
    ("t_p_weissiteme", "수질측정망공단배수지점", "환경 · 지질", "LT_P_WEISSITEME", "wfs"),
    ("t_p_weissitemd", "수질측정망농업용수지점", "환경 · 지질", "LT_P_WEISSITEMD", "wfs"),
    ("t_p_weissitemb", "수질측정망호소수지점", "환경 · 지질", "LT_P_WEISSITEMB", "wfs"),
    ("t_c_wgisarwet", "습지보호구역", "기타 주제도", "LT_C_WGISARWET", "wfs"),
    ("t_c_adsigg", "시군구", "기타 주제도", "LT_C_ADSIGG", "wfs"),
    ("t_p_c1trafficlight", "신호등", "기타 주제도", "LT_P_C1TRAFFICLIGHT", "wfs"),
    ("t_c_b1safetysign", "안전표지", "기타 주제도", "LT_C_B1SAFETYSIGN", "wfs"),
    ("t_p_b1safetysign", "안전표지(점)", "기타 주제도", "LT_P_B1SAFETYSIGN", "wfs"),
    ("t_pa_cbnd_bonbun", "연속지적도", "기타 주제도", "LP_PA_CBND_BONBUN", "wfs"),
    ("t_dt_d002", "연속지적도형정보", "기타 주제도", "DT_D002", "wfs"),
    ("t_c_uh501", "유통단지", "산업 · 개발", "LT_C_UH501", "wfs"),
    ("t_c_ademd", "읍면동", "기타 주제도", "LT_C_ADEMD", "wfs"),
    ("t_c_aistemp", "임시비행금지공역", "항공 · 군사", "LT_C_AISTEMP", "wfs"),
    ("t_c_uf602", "임업 및 산촌 진흥권역", "기타 주제도", "LT_C_UF602", "wfs"),
    ("t_c_uh402", "자유무역지역지정및운영", "기타 주제도", "LT_C_UH402", "wfs"),
    ("t_c_a5parkinglot", "주차면", "기타 주제도", "LT_C_A5PARKINGLOT", "wfs"),
    ("t_p_a1node", "주행경로노드", "기타 주제도", "LT_P_A1NODE", "wfs"),
    ("t_l_a2link", "주행경로링크", "기타 주제도", "LT_L_A2LINK", "wfs"),
    ("t_p_c6postpoint", "지주", "기타 주제도", "LT_P_C6POSTPOINT", "wfs"),
    ("t_c_a3drivewaysection", "차도구간", "기타 주제도", "LT_C_A3DRIVEWAYSECTION", "wfs"),
    ("t_l_c3vehicleprotectionsaf", "차량방호안전시설", "기타 주제도", "LT_L_C3VEHICLEPROTECTIONSAFETY", "wfs"),
    ("t_p_c2kilopost", "킬로포스트", "기타 주제도", "LT_P_C2KILOPOST", "wfs"),
    ("t_dt_d160", "토지소유공간정보", "기타 주제도", "DT_D160", "wfs"),
    ("t_c_tfismpa", "해양보호구역", "기타 주제도", "LT_C_TFISMPA", "wfs"),
    ("t_c_aiscatc", "훈련구역", "항공 · 군사", "LT_C_AISCATC", "wfs"),
]
